### ISSUE TITLE
Change of sequence of labels

### ISSUE THREAD

**Issue by vishal1905** [atulapra/Emotion-detection#33]
why you have changed the sequence of emotions from {0:"Angry", 1:"Disgust", 2:"Fear", 3:"Happy", 4:"Sad", 5:"Surprise", 6:"Neutral"} to {0: "Angry", 1: "Disgusted", 2: "Fearful", 3: "Happy", 4: "Neutral", 5: "Sad", 6: "Surprised"} in emotions.py?

**Comment by niyazaki** [comment]
Because the model gives the index of the corresponding emotion in the order of the folders he had when training. Which are alphabetical, so you need to have a dictionnary of labels in alphabetical order.

If your question is why he changed "fear" to "fearful" it's only because this is what is displayed. It seems more correct. That's my opinion.

Hope it helps
